### ISSUE TITLE
1) reduzir o tamanho da foto de forma que caiba na tela de um iPhone 5 um feed item inteiro , inclusive a categoria e os botões de interação 

### ISSUE THREAD

**Issue by jeanstreleski** [temantrip/temantrip-ios#1]
1) reduzir o tamanho da foto de forma que caiba na tela de um iPhone 5 um feed item inteiro , inclusive a categoria e os botões de interação 
![img_8246](https://cloud.githubusercontent.com/assets/6921246/8721876/37b4aba2-2b95-11e5-9cee-42f1424a7667.PNG)

**Comment by tiagoporangaba** [comment]
confirma se isso ainda acontece?
