### ISSUE TITLE
20) as telas não estão responsivas no iPhone 5

### ISSUE THREAD

**Issue by jeanstreleski** [temantrip/temantrip-ios#20]
20) as telas não estão responsivas no iPhone 5

**Comment by tiagoporangaba** [comment]
posta umas screenshots ai! além das que você já postou...

mas não tem jeito, vou ter que ficar com o seu cel do meu lado, testando e ajustando, até ficar bom no 5 e 6. 

vou deixar os ajustes de layout por último, quando fecharmos todo o design. senão vai ter retrabalho.

**Comment by tiagoporangaba** [comment]
parece que consegui!
