### ISSUE TITLE
22) no detalhe da carona, os textos fixos (nome , mensagem etc) são clicaveis e mudam de cor deixando impossível ler . Nesta mesma tela. As barras de texto ficaram muito largas e para pouca informação. A sugestão é deixar tudo menor para dar destaque aos dados da carona Foto 12

### ISSUE THREAD

**Issue by jeanstreleski** [temantrip/temantrip-ios#22]
22) no detalhe da carona, os textos fixos (nome , mensagem etc) são clicaveis e mudam de cor deixando impossível ler . Nesta mesma tela.
As barras de texto ficaram muito largas e para pouca informação. A sugestão é deixar tudo menor para dar destaque aos dados da carona Foto 12
![img_8258](https://cloud.githubusercontent.com/assets/6921246/8722012/9afcc720-2b96-11e5-9ed9-e59ebe342f2c.PNG)

**Comment by tiagoporangaba** [comment]
done!
