### ISSUE TITLE
6) a seleção de lugar no show off no esta aparecendo atrás do teclado Foto 3

### ISSUE THREAD

**Issue by jeanstreleski** [temantrip/temantrip-ios#6]
6) a seleção de lugar no show off no esta aparecendo atrás do teclado Foto 3
![img_8248](https://cloud.githubusercontent.com/assets/6921246/8721924/9d7acaac-2b95-11e5-9a85-9fc00ac5ba4d.PNG)

**Comment by tiagoporangaba** [comment]
done!
