### ISSUE TITLE
7 ) as opções de rating da experiência estão muito grandes e portanto estão cortando na horizontal . Não dá pra ler a última opção Foto4

### ISSUE THREAD

**Issue by jeanstreleski** [temantrip/temantrip-ios#7]
7 ) as opções de rating da experiência estão muito grandes e portanto estão cortando na horizontal . Não dá pra ler a última opção
Foto4
![img_8249](https://cloud.githubusercontent.com/assets/6921246/8721935/b1f79bcc-2b95-11e5-9054-e45fff3a02f6.PNG)

**Comment by tiagoporangaba** [comment]
isso parece que eu corrigi!
