### ISSUE TITLE
9) a tela não está centralizando no iPhone 5 . O botão concluir esta mais à direita Foto 4

### ISSUE THREAD

**Issue by jeanstreleski** [temantrip/temantrip-ios#9]
9) a tela não está centralizando no iPhone 5 . O botão concluir esta mais à direita Foto 4
![img_8250](https://cloud.githubusercontent.com/assets/6921246/8721947/d3b41de4-2b95-11e5-919b-160b9d1598d2.PNG)

**Comment by tiagoporangaba** [comment]
retiramos as notas por enquanto!
